# Generated by Django 5.0.6 on 2024-06-30 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
